version: '3.9'
services:
  postgres:
    container_name: postgresql_parcial2
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: parcial2
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin_parcial2
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5051:80"
